### ISSUE TITLE
namespace_map not passed to page.py

### ISSUE THREAD

**Issue by carlinmack** [mediawiki-utilities/python-mwxml#16]
trying to parse the following XML:

```XML
<page>
    <title>Talk:Atlas Shrugged</title>
    <ns>1</ns>
    <id>128</id>
    <revision>
      <id>233328</id>
      <timestamp>2001-01-30T20:51:36Z</timestamp>
      <contributor>
        <username>TimShell</username>
        <id>4938</id>
      </contributor>
      <comment>*</comment>
      <model>wikitext</model>
      <format>text/x-wiki</format>
      <text xml:space="preserve">I am developing the AtlasShrugged section of Wikipedia as a test to push the envelope of what is possible with a wiki.  I hope to show that a wiki-based encyclopedia is not merely the same old encyclopedia with a different development and editing system, but a tool that allows types of content not easily integrated into conventional encyclopedias.



I chose AtlasShrugged for this project for a few reasons.  I am familiar with it so can do a passable job in summarizing it.  It is very large and complex, making it a good test of what is possible.  Often people who are into AtlasShrugged are _really_ into it, so there are likely people who will contribute and who will be interested in the section.  There is a movie coming out, so interest in AtlasShrugged might be expected to surge soon - it would be good for the project if we were able to sate that interest with a really cool AtlasShrugged section.

</text>
      <sha1>8h7rtham3lmiwm6zzr9jptz84eviu8z</sha1>
    </revision>
    <revision>
      <id>677884</id>
      <parentid>233328</parentid>
      <timestamp>2002-02-25T15:43:11Z</timestamp>
      <contributor>
        <username>Conversion script</username>
        <id>1226483</id>
      </contributor>
      <minor />
      <comment>Automated conversion</comment>
      <model>wikitext</model>
      <format>text/x-wiki</format>
      <text xml:space="preserve">I am developing the AtlasShrugged section of Wikipedia as a test to push the envelope of what is possible with a wiki.  I hope to show that a wiki-based encyclopedia is not merely the same old encyclopedia with a different development and editing system, but a tool that allows types of content not easily integrated into conventional encyclopedias.

I chose AtlasShrugged for this project for a few reasons.  I am familiar with it so can do a passable job in summarizing it.  It is very large and complex, making it a good test of what is possible.  Often people who are into AtlasShrugged are _really_ into it, so there are likely people who will contribute and who will be interested in the section.  There is a movie coming out, so interest in AtlasShrugged might be expected to surge soon - it would be good for the project if we were able to sate that interest with a really cool AtlasShrugged section.
----
Then we ought to have a similar LordOfTheRings section, too! -- [[Larry Sanger]]

:''See also :'' [[AtlasShrugged]]</text>
      <sha1>b7k6fyokhktsdin9eujw8emcautikcg</sha1>
    </revision>
</page>
``` 

I got the following error:
```
Traceback (most recent call last):
  File "parse.py", line 117, in <module>
    for page in dump:
  File "/u/ckm8gz/.local/lib/python3.8/site-packages/mwxml/iteration/dump.py", line 92, in load_items
    yield cls.process_item(item_element, namespace_map)
  File "/u/ckm8gz/.local/lib/python3.8/site-packages/mwxml/iteration/dump.py", line 97, in process_item
    return Page.from_element(item_element, namespace_map)
  File "/u/ckm8gz/.local/lib/python3.8/site-packages/mwxml/iteration/page.py", line 97, in from_element
    mapped_namespace, title = extract_namespace(page_name, namespace_map)
  File "/u/ckm8gz/.local/lib/python3.8/site-packages/mwxml/iteration/page.py", line 121, in extract_namespace
    if ns_name in namespace_map:
TypeError: argument of type 'NoneType' is not iterable
```

This is the first talkpage (namespace=1) I've tried to parse, please advise if there is a flag I can set. From what I can see you can't pass in namespaces.

Thanks for your work!

**Comment by carlinmack** [comment]
Oh I see, I'm actually purposely discarding that header information and parsing xml files this format:

```XML
<page>
</page>
<page>
</page>
```

by doing 

```python
import mwxml

test_dump = "test.xml"
dump = mwxml.Dump.from_page_xml(open(test_dump))

for page in dump:
    for revision in page:
        print(revision.page.namespace)
        print(revision.user.id)
```

The reason for discarding the information is because I'm splitting the dumps into partitions for using on multiple cores. I'm aware of mwxml.map() but I haven't investigated if it will work for my use case.

I suppose I will add the header and closing `</mediawiki>` tag to resolve this issue.

Thanks, feel free to close.
