### ISSUE TITLE
Use of qsize leads to NotImplementedError on macOS

### ISSUE THREAD

**Issue by halfak** [mediawiki-utilities/python-mwxml#8]
Originally filed by @harej in https://github.com/mediawiki-utilities/python-mwrefs/issues/14

```
Norepinephrine:Citationbase jh$ mwrefs extract enwiki-20170901-pages-meta-history10.xml-p2969251p3015717.bz2
page_id	page_title	rev_id	rev_timestamp	reference
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/mwrefs", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mwcli/router.py", line 56, in main
    module.main(sys.argv[2:])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mwrefs/utilities/extract.py", line 35, in main
    run(dump_files)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mwrefs/utilities/extract.py", line 53, in run
    for vals in xml_dump.map(dump_files, process_dump):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mw/xml_dump/map.py", line 59, in map
    threads = max(1, min(int(threads), pathsq.qsize()))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
Norepinephrine:Citationbase jh$
```

According to The Manual, qsize() in the multiprocessing module:
> may raise NotImplementedError on Unix platforms like Mac OS X where sem_getvalue() is not implemented.

Source: https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Queue.qsize

**Comment by halfak** [comment]
Interesting.  qsize() is important but we can probably avoid it in this instance.

**Comment by halfak** [comment]
Oh!  Actually this looks like it is only an issue for `mw` -- the old mediawiki-utilities library.
